### ISSUE TITLE
Error generated with the new image of dd-agent

### ISSUE THREAD

**Issue by mohithraj** [DataDog/dd-agent#3504] opened 2017-09-05 10:34 UTC
**Log of /var/log/datadog/collector.log**

```
2017-09-05 10:19:11 UTC | CRITICAL | dd.collector | checks.docker_daemon(docker_daemon.py:248) | Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
2017-09-05 10:19:11 UTC | WARNING | dd.collector | checks.docker_daemon(__init__.py:702) | Initialization failed. Will retry at next iteration
2017-09-05 10:19:11 UTC | INFO | dd.collector | checks.http_check(network_checks.py:110) | Stopping Thread Pool
2017-09-05 10:19:11 UTC | INFO | dd.collector | checks.http_check(network_checks.py:95) | Starting Thread Pool
ERROR | dd.collector | checks.http_check(network_checks.py:161) | Failed to process instance 'process_name'.
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/network_checks.py", line 147, in _process
    statuses = self._check(instance)
  File "/opt/datadog-agent/agent/checks.d/http_check.py", line 277, in _check
    self.gauge('network.http.response_time', running_time, tags=tags_list)
  File "/opt/datadog-agent/agent/checks/__init__.py", line 416, in gauge
    self.aggregator.gauge(metric, value, tags, hostname, device_name, timestamp)
  File "/opt/datadog-agent/agent/aggregator.py", line 915, in gauge
    self.submit_metric(name, value, 'g', tags, hostname, device_name, timestamp)
  File "/opt/datadog-agent/agent/aggregator.py", line 902, in submit_metric
    context = (name, tuple(sorted(set(tags))), hostname, device_name)
TypeError: unhashable type: 'dict'
```

I am running this on aws kubernetes cluster 1.7

**Log of dogstatsd.log**

 ```
WARNING | dd.dogstatsd | utils.dockerutil(dockerutil.py:94) | Error while detecting orchestrator: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
2017-09-05 09:25:53 UTC | ERROR | dd.dogstatsd | collector(kubeutil.py:87) | Couldn't find any configuration file for the kubernetes check.
2017-09-05 09:25:53 UTC | WARNING | dd.dogstatsd | utils.dockerutil(dockerutil.py:239) | Unable to find docker host hostname. Trying default route
2017-09-05 09:25:53 UTC | ERROR | dd.dogstatsd | collector(kubeutil.py:193) | object of type 'NoneType' has no len()
2017-09-05 09:25:53 UTC | INFO | dd.dogstatsd | utils.pidfile(pidfile.py:35) | Pid file is: /opt/datadog-agent/run/dogstatsd.pid
2017-09-05 09:25:53 UTC | INFO | dd.dogstatsd | daemon(daemon.py:157) | Starting
2017-09-05 09:25:53 UTC | INFO | dd.dogstatsd | dogstatsd(dogstatsd.py:398) | Listening on socket address: ('::ffff:0.0.0.0', 8125, 0, 0)
2017-09-05 09:25:53 UTC | INFO | dd.dogstatsd | dogstatsd(dogstatsd.py:216) | Reporting to http://localhost:17123 every 10s
2017-09-05 09:26:03 UTC | INFO | dd.dogstatsd | dogstatsd(dogstatsd.py:261) | Flush #1: flushed 14 metrics, 0 events, and 1 service check run
2017-09-05 09:26:13 UTC | INFO | dd.dogstatsd | dogstatsd(dogstatsd.py:261) | Flush #2: flushed 22 metrics, 0 events, and 1 service check run
```

**log of forwarder.log**
```
cat /var/log/datadog/forwarder.log
2017-09-05 09:25:53 UTC | INFO | dd.forwarder | root(ddagent.py:146) | Done with custom emitters
2017-09-05 09:25:53 UTC | INFO | dd.forwarder | forwarder(ddagent.py:542) | Listening on port 17123
2017-09-05 09:25:57 UTC | INFO | dd.forwarder | transaction(transaction.py:177) | Flushing 1 transaction during flush #1
2017-09-05 09:25:58 UTC | INFO | dd.forwarder | transaction(transaction.py:177) | Flushing 1 transaction during flush #2
```
## /etc/init.d/datadog-agent status
Datadog Agent (supervisor) is running all child processes
# 
## /etc/init.d/datadog-agent info
  _Checks
  ======_
  
    ntp (5.16.0)
    ------------
      - Collected 0 metrics, 0 events & 0 service checks
  
    disk (5.16.0)
    -------------
      - instance #0 [OK]
      - Collected 32 metrics, 0 events & 0 service checks
  
    docker_daemon (5.16.0)
    ----------------------
      - instance #0 [WARNING]
          Warning: Initialization failed. Will retry at next iteration
      - Collected 0 metrics, 0 events & 1 service check
  
    http_check (5.16.0)
    -------------------
      - instance #0 [OK]
      - Collected 0 metrics, 0 events & 0 service checks
  
    jmx (5.16.0)
    ------------
      - instance #jmx-localhost-7199 [OK] collected 176 metrics
      - Collected 176 metrics, 0 events & 0 service checks

**Comment by hush-hush** [comment] 2017-09-05 15:29
Hi @mohithraj,

Could you paste the configuration file for your HTTP check (making sure you remove any sensitive information) ?

Also, could you give me the tag and hash of the docker image you are using ? This will help us reproduce your issue.

Thanks.Hi @mohithraj,

Could you paste the configuration file for you http check (making sure you remove any sensitive information) ?

Also could you give me the tag and hash of the docker image you are using ? This will help us reproduce your issue.

Thanks.

**Comment by hush-hush** [comment] 2017-09-06 09:40
Hi @mohithraj,

The tag list in your configuration must be a list of strings. In YAML, since you insert a space between `url:` and `SERVICE_NAME` your `tags` became a list of dict.

here is the right configuration you want (which will produce a list of string):
```
tags:
  - url:SERVICE_NAME
```

I agree this is a pretty bad error that should have been logged in the info page. I opened an issue in our backlog to fix this.

I'm closing this issue but feel free to reopen it if needed.
Thanks for your patience.

**Closed by hush-hush** 2017-09-06 09:40 UTC
