### ISSUE TITLE
Datadog docker agent stops sending data to DD SaaS after collector process Exits

### ISSUE THREAD

**Issue by ksunny** [DataDog/dd-agent#2966] opened 2016-10-27 05:08 UTC
Hi,
I have seen this happening recently on a number of our instances, that DD agent has stopped sending data to the SaaS DD.
On investigation I found that the collector process received  a SIGKILL signal (not sure where and why is it getting the signal) and terminates. After this the collector process does come back up with a different PID. But data forwarding to the SaaS is not happening:

``` bash
$ docker logs dd-agent-worker
2016-10-26 05:40:09,906 CRIT Supervisor running as root (no user in config file)
2016-10-26 05:40:09,986 INFO RPC interface 'supervisor' initialized
2016-10-26 05:40:09,986 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-10-26 05:40:09,986 INFO supervisord started with pid 1
2016-10-26 05:40:10,987 INFO spawned: 'dogstatsd' with pid 33
2016-10-26 05:40:10,988 INFO spawned: 'go-metro' with pid 34
2016-10-26 05:40:10,989 INFO spawned: 'forwarder' with pid 35
2016-10-26 05:40:10,990 INFO spawned: 'collector' with pid 36
2016-10-26 05:40:10,991 INFO spawned: 'jmxfetch' with pid 37
2016-10-26 05:40:12,994 INFO success: go-metro entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2016-10-26 05:40:14,113 INFO success: jmxfetch entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2016-10-26 05:40:16,119 INFO success: dogstatsd entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-10-26 05:40:16,119 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-10-26 05:40:16,119 INFO success: collector entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-10-26 05:40:16,499 INFO exited: go-metro (exit status 0; expected)
2016-10-26 05:40:16,860 INFO exited: jmxfetch (exit status 0; expected)
2016-10-26 06:20:23,590 INFO exited: collector (terminated by SIGKILL; not expected)
2016-10-26 06:20:24,592 INFO spawned: 'collector' with pid 559
2016-10-26 06:20:29,738 INFO success: collector entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
```

We have CoreOs running of AWS instances. The DD agent runs as a docker container. We use the latest image available.

Steps to Reproduce:
- Run a docker dd agent. Start seeing the metrics on DD SaaS.
- login to the container and list the processes running:

```
# ps -ef 
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 Oct11 ?        00:03:22 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/bin/supervisord -n -c /etc/dd-agent/supervisor.conf
root        33     1  0 Oct11 ?        00:14:34 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/dogstatsd.py --use-local-forwarder
root        35     1  0 Oct11 ?        00:18:48 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/ddagent.py
root        36     1  0 Oct11 ?        00:49:47 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/agent.py foreground --use-local-forwarder
root     27887     0  0 05:33 ?        00:00:00 /bin/bash
root     27941     0  1 05:36 ?        00:00:00 /bin/bash
root     27952 27941  0 05:36 ?        00:00:00 ps -ef

- kill -9 36
```
- The agent starts back up with a different PID:

```
 ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 05:40 ?        00:00:00 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/bin/supervisord -n -c /etc/dd-agent/supervisor.conf
root        33     1  0 05:40 ?        00:00:02 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/dogstatsd.py --use-local-forwarder
root        35     1  0 05:40 ?        00:00:02 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/ddagent.py
root        79     0  0 05:41 ?        00:00:00 /bin/bash
root       559     1  3 06:20 ?        00:00:00 /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/agent.py foreground --use-local-forwarder
```

-Check DD SaaS it will not start receiving the data.

**Comment by masci** [comment] 2016-10-27 06:33
Hi @ksunny and thanks for reporting!

To help us investigate, could you please send us a flare from one of the involved agents? Instructions are [here](https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command).

**Comment by remh** [comment] 2016-10-27 10:38
I tried to reproduce the issue on core os 1122.3.0 and was unable. As per @masci a flare would help a lot in this case.

**Comment by ksunny** [comment] 2016-11-03 09:01
Hi guys, 
Apologies for the delay here. I have uploaded 2 flares to https://help.datadoghq.com/hc/requests/70003

So there are two scenarios: 
# the first one datadog-agent-2016-11-03-06-59-50.tar.bz2 is from a host that never reported back DD SaaS after the dd agent container came up.

# the second one datadog-agent-2016-11-03-07-02-53.tar.bz2 is from a host that stopped reporting after some time (few days).

**Comment by mukunm** [comment] 2017-09-06 22:47
Any updates on this? I still see this with the same setup as described above. 

```
2017-09-06 22:38:40,341 CRIT Supervisor running as root (no user in config file)
2017-09-06 22:38:40,400 INFO RPC interface 'supervisor' initialized
2017-09-06 22:38:40,401 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-09-06 22:38:40,401 INFO supervisord started with pid 1
2017-09-06 22:38:41,403 INFO spawned: 'process-agent' with pid 13
2017-09-06 22:38:41,404 INFO spawned: 'trace-agent' with pid 14
2017-09-06 22:38:41,411 INFO spawned: 'forwarder' with pid 18
2017-09-06 22:38:41,412 INFO spawned: 'dogstatsd' with pid 19
2017-09-06 22:38:41,414 INFO spawned: 'jmxfetch' with pid 21
2017-09-06 22:38:41,416 INFO spawned: 'go-metro' with pid 22
2017-09-06 22:38:41,423 INFO spawned: 'collector' with pid 25
2017-09-06 22:38:43,478 INFO success: go-metro entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2017-09-06 22:38:44,479 INFO success: jmxfetch entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2017-09-06 22:38:46,849 INFO success: process-agent entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2017-09-06 22:38:46,849 INFO success: trace-agent entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2017-09-06 22:38:46,849 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2017-09-06 22:38:46,849 INFO success: dogstatsd entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2017-09-06 22:38:46,849 INFO success: collector entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2017-09-06 22:38:47,397 INFO exited: go-metro (exit status 0; expected)
2017-09-06 22:38:49,635 INFO exited: jmxfetch (exit status 0; expected)
2017-09-06 22:39:56,458 WARN received SIGTERM indicating exit request
2017-09-06 22:39:56,458 INFO waiting for process-agent, trace-agent, forwarder, dogstatsd, collector to die
2017-09-06 22:39:56,460 INFO stopped: trace-agent (exit status 0)
2017-09-06 22:39:56,463 INFO stopped: process-agent (exit status 0)
2017-09-06 22:39:56,502 INFO stopped: forwarder (exit status 0)
2017-09-06 22:39:56,509 INFO stopped: collector (exit status 0)
2017-09-06 22:39:56,525 INFO stopped: dogstatsd (exit status 0)
```

**Comment by masci** [comment] 2017-09-07 08:41
Hi @mukunm, thanks for using Datadog.

For your request, please contact our [support](http://docs.datadoghq.com/help/) and send them your [logs](https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command).

I'm closing this issue since a flare would be needed in any case and this can be better handled by our support team.

Thanks.

**Closed by masci** 2017-09-07 08:41 UTC
Labels: triage
