### ISSUE TITLE
Dogstream doesn't support custom tags

### ISSUE THREAD

**Issue by remh** [DataDog/dd-agent#807] opened 2014-01-23 21:46 UTC
It only supports device_name and aggregates the rest.

**Comment by remh** [comment] 2016-01-06 22:32
Closing as we are working on finding a better replacement for dogstream.

**Comment by justiniso** [comment] 2016-01-08 04:42
> Closing as we are working on finding a better replacement for dogstream.

@remh what's wrong with dogstream? Why is it being replaced?

**Comment by ewdurbin** [comment] 2016-08-02 14:52
this is not a well specified issue, we have determined that we are seeing funny issues with dogstreams and tags. we would like to work on a fix but it's unclear where to get started looking to resolve.

if more information was provided on what needs to be done to resolve dogstream tag handling, I'd be happy to take a closer look.

**Comment by justiniso** [comment] 2016-08-02 15:05
Hey @ewdurbin thanks for surfacing this again! Please don't close the issue as being unreproducible though. The problem is actually well-documented in some of the related issues/pr's linked above

https://github.com/DataDog/dd-agent/issues/1304
https://github.com/DataDog/dd-agent/pull/2103

Those were closed to consolidate with this one (which is admittedly not well specified) being the canonical issue. Please take a look at my PR https://github.com/DataDog/dd-agent/pull/2103. I've been running a version of the agent which implements that change on a service processing 8,000 log lines per second for several months now with the correct behavior. I'd love to remove that hack if this gets merged into the agent! 😄

**Comment by justiniso** [comment] 2016-10-27 04:38
@clutchski this is the dogstream issue I was talking about where you are limited to one unique series per second. Aggregation is rolling up custom tags to the first occurrence of that metric (https://github.com/DataDog/dd-agent/issues/1304 does a better job of describing the specific issue). When you have thousands of log lines per second, this is a show-stopper. When my PR was closed, it sounded like there was something coming in 6.0.0 that fixed the issue, but now it seems like that's not the case. I think this is a bug that can have a pretty significant impact on reporting for anyone using dogstream with tags. 

For my service ingesting 10,000 req/s, the math was very obviously wrong which led me to here. But for services logging with much lower volumes (e.g. 2-100 lines/s), this bug can go completely undetected and create wildly inaccurate reports.

**Comment by alexef** [comment] 2016-12-05 13:53
We are also affected by this issue - what is the plan. What kind of details do you need @ewdurbin ?

**Closed** 2017-01-30 17:07 UTC
Labels: wontfix
