### ISSUE TITLE
Exception: Missing data from Win32_PerfFormattedData_W3SVC_WebService

### ISSUE THREAD

**Issue by jeremymv2** [DataDog/dd-agent#1526] opened 2015-04-09 18:20 UTC
New agent install with the iis check enabled and am getting this error.

Agent version
5.2.3
Platform
Windows-2012Server-6.2.9200
Python version
2.7.8

  File "c:\Program Files (x86)\Datadog\Datadog Agent\files\..\checks.d\iis.py", line 68, in check
Exception: Missing data from Win32_PerfFormattedData_W3SVC_WebService

Also referenced here:
https://github.com/DataDog/dd-agent/issues/895

**Comment by LeoCavaille** [comment] 2015-04-09 18:28
@jeremymv2 thanks for reporting this, we'll investigate.

**Comment by yannmh** [comment] 2015-04-14 20:23
@jeremymv2 If you have Powershell installed on your machine, could you please try to run `Get-WmiObject Win32_PerfFormattedData_W3SVC_WebService` ([Get-WmiObject](https://technet.microsoft.com/en-us/library/hh849824.aspx)) with and without administrator privileges ?

This would help to know if the issue is on the agent side or on IIS, not exposing correctly object information. 
I set up an environment as close as yours but didn't manage to reproduce this issue.

Thanks a lot

**Comment by yannmh** [comment] 2015-06-04 21:00
@jeremymv2 haven't heard back from you. Are you still experiencing the issue ?

**Comment by yannmh** [comment] 2015-07-27 21:54
Closing. Please feel free to re-open if you're still experiencing the issue.

**Closed by yannmh** 2015-07-27 21:54 UTC
Labels: triage
