### ISSUE TITLE
dogstatsd_interval and dogstatsd_normalize options are dead

### ISSUE THREAD

**Issue by LotharSee** [DataDog/dd-agent#1328] opened 2015-01-29 16:45 UTC
While still present in the example configuration files, `dogstatsd_interval` and `dogstatsd_normalize` are no longer used in the code.
This disappearance seems to be related to a logic change in the aggregator.

While we could just remove them, it could make sense to bring them back. 
I am not sure about `dogstatsd_normalize` (it would just multiply the values with a constant that don't have a real meaning), but `dogstatsd_interval` is still important.

I checked the code, the flush interval and the aggregator interval are 2 important attributes that we should be able to configure. But we only use their default values `DOGSTATSD_FLUSH_INTERVAL` and `DOGSTATSD_AGGREGATOR_BUCKET_SIZE`.
It should be deadly simple to make them configurable.

**Comment by remh** [comment] 2015-02-27 16:38
Duplicate of #805

**Closed by remh** 2015-02-27 16:38 UTC
