### ISSUE TITLE
datadog agent monitors readonly disks by default

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/dd-agent#1857] opened 2015-08-25 11:46 UTC
It seems that datadog agent monitor readonly disks, which doesn't make any sense and is triggering false positive errors. 

Imagine that this will monitor the cdrom drive of any VM or physical machines and will alert you that the is no free space.

This is a request for adding a default filter that would eliminate the `ro` (readonly) mounts from the monitored diska.

I am not sure how the agent lists the disk but my mount command does contain a `(ro` text for all mounts that are read only. not that his piece of text is part of the mount options.

**Comment by yannmh** [comment] 2015-08-25 13:34
Hi @ssbarnea,

Thanks for reporting (and the further details !). We adressed the issue in #1786. 
It'll be out next week with the 5.5.0 agent release :rocket:

**Comment by remh** [comment] 2015-08-25 15:07
Duplicate of https://github.com/DataDog/dd-agent/issues/1716

**Closed by remh** 2015-08-25 15:07 UTC
