### ISSUE TITLE
DataDog Docker integration issue on Debian Jessie

### ISSUE THREAD

**Issue by czerasz** [DataDog/dd-agent#2680] opened 2016-07-13 09:34 UTC
I'm getting the following on my Debian DigitalOcean dropplet:

```
docker_daemon
-------------
  - instance #0 [WARNING]
      Warning: Initialization failed. Will retry at next iteration
  - Collected 0 metrics, 0 events & 1 service check
```

Below the configuration file (recommended on the integration page):

```
$ cat /etc/dd-agent/conf.d/docker_daemon.yaml
init_config:

instances:
    - url: "unix://var/run/docker.sock"
      new_tag_names: true
```

Here the full info output:

```
$ /etc/init.d/datadog-agent info
===================
Collector (v 5.8.4)
===================

  Status date: 2016-07-12 12:49:32 (3s ago)
  Pid: 1021
  Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
  Python Version: 2.7.11, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log, syslog:/dev/log

  Clocks
  ======
  
    NTP offset: 0.46 s
    System UTC time: 2016-07-12 16:49:35.680506
  
  Paths
  =====
  
    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d
  
  Hostnames
  =========
  
    socket-hostname: debian-1gb-fra1-xx-01
    hostname: debian-1gb-fra1-xx-01
    socket-fqdn: debian-1gb-fra1-xx-01
  
  Checks
  ======
  
    nginx
    -----
      - instance #0 [OK]
      - Collected 7 metrics, 0 events & 2 service checks
  
    network
    -------
      - instance #0 [OK]
      - Collected 27 metrics, 0 events & 1 service check
  
    ntp
    ---
      - Collected 0 metrics, 0 events & 1 service check
  
    disk
    ----
      - instance #0 [OK]
      - Collected 32 metrics, 0 events & 1 service check
  
    docker_daemon
    -------------
      - instance #0 [WARNING]
          Warning: Initialization failed. Will retry at next iteration
      - Collected 0 metrics, 0 events & 1 service check
  
  
  Emitters
  ========
  
    - http_emitter [OK]

===================
Dogstatsd (v 5.8.4)
===================

  Status date: 2016-07-12 12:49:35 (1s ago)
  Pid: 1018
  Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
  Python Version: 2.7.11, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log, syslog:/dev/log

  Flush count: 16
  Packet Count: 0
  Packets per second: 0.0
  Metric count: 1
  Event count: 0
  Service check count: 0

===================
Forwarder (v 5.8.4)
===================

  Status date: 2016-07-12 12:49:35 (2s ago)
  Pid: 1020
  Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
  Python Version: 2.7.11, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log, syslog:/dev/log

  Queue Size: 463 bytes
  Queue Length: 1
  Flush Count: 48
  Transactions received: 24
  Transactions flushed: 23
  Transactions rejected: 0
```

Docker is installed and the `dd-agent` user has access to it:

```
$ su dd-agent
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                         NAMES
51a802837dd8        nginx               "nginx -g 'daemon off"   10 minutes ago      Up 2 minutes        0.0.0.0:80->80/tcp, 443/tcp   nginx
```

**Comment by hkaj** [comment] 2016-07-13 09:45
Hi @czerasz 

Thank you for describing this issue with such great detail!
Can you send a flare to our support team from the droplet with this failing agent? This will send us logs from the agent which will help us investigate this issue.

Instructions for sending a flare can be found here: https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command

**Comment by czerasz** [comment] 2016-07-13 09:59
@hkaj unfortunately I already removed this instance :-(
The droplet was using `Debian 8.5 x64`.

**Comment by brandonstevens** [comment] 2016-08-04 02:46
I think I was able to reproduce this error. I had the same warning above plus the additional error in collector.log:

```2016-08-04 02:34:02 UTC | CRITICAL | dd.collector | checks.docker_daemon(docker_daemon.py:205) | Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))
2016-08-04 02:34:02 UTC | WARNING | dd.collector | checks.docker_daemon(__init__.py:654) | Initialization failed. Will retry at next iteration```

In my case, I did the following:

1. Install datadog-agent
2. Install docker
3. Add dd-agent to the docker group
4. Copy the example docker datadog config
5. Reload the datadog-agent service

**Note:** I did not restart the datadog-agent service after adding the dd-agent user to the docker group. 

The issue is that the datadog-agent process does not have permissions to the docker socket. Group additions aren't applied to running services so to avoid the above issue, restart the datadog-agent service instead of reloading it. That also explains why running a new process (i.e. `sudo -u dd-agent docker ps`) is able to access the docker socket.

I can keep the environment around if you'd like me to pull any more information from it.

**Comment by dlyub** [comment] 2016-08-23 19:14
We're seeing a very similar issue. As soon as this got added 'collect_events: true' to the yaml file same exact errors started showing up. No issues reported when docker_daemon is enabled, but collects no metrics.

**Comment by hkaj** [comment] 2016-08-24 08:58
Hi @dlyub 
Your issue seems to be a different one (although linked to docker_daemon too). Can you open a separate issue and paste some parts of your `collector.log` containing the error you see please? The collector.log is generally located in `/var/log/datadog/`.
Thanks

**Comment by hkaj** [comment] 2016-08-24 08:59
I am also going to close this issue as it looks like a permission issue that an agent restart solves. Feel free to reopen if anything new arises.

**Closed by hkaj** 2016-08-24 08:59 UTC

**Comment by adilr00t** [comment] 2016-09-14 18:18
I'm having a similar issue

#### my dd-agent info
```
===================
Collector (v 5.8.5)
===================

  Status date: 2016-09-14 18:07:04 (8s ago)
  Pid: 565
  Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log, syslog:/dev/log

  Clocks
  ======
  
    NTP offset: 0.0048 s
    System UTC time: 2016-09-14 18:07:12.972506
  
  Paths
  =====
  
    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d
  
  Hostnames
  =========
  
    ec2-hostname: xxxxxxx
    local-ipv4: xxxxxxx
    local-hostname: xxxxxx
    socket-hostname: xxxxxxx
    public-hostname: xxxxxxx
    hostname: xxxxxxx
    instance-id: xxxxxxx
    public-ipv4: xxxxxxx
    socket-fqdn: xxxxxxx
  
  Checks
  ======
  
    ntp
    ---
      - Collected 0 metrics, 0 events & 1 service check
  
    disk
    ----
      - instance #0 [OK]
      - Collected 32 metrics, 0 events & 1 service check
  
    network
    -------
      - instance #0 [OK]
      - Collected 27 metrics, 0 events & 1 service check
  
    docker_daemon
    -------------
      - instance #0 [WARNING]
          Warning: Initialization failed. Will retry at next iteration
      - Collected 0 metrics, 0 events & 1 service check
  
  
  Emitters
  ========
  
    - http_emitter [OK]

===================
Dogstatsd (v 5.8.5)
===================

  Status date: 2016-09-14 18:07:09 (4s ago)
  Pid: 562
  Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log, syslog:/dev/log

  Flush count: 20
  Packet Count: 0
  Packets per second: 0.0
  Metric count: 1
  Event count: 0
  Service check count: 0

===================
Forwarder (v 5.8.5)
===================

  Status date: 2016-09-14 18:07:10 (3s ago)
  Pid: 564
  Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log, syslog:/dev/log

  Queue Size: 0 bytes
  Queue Length: 0
  Flush Count: 71
  Transactions received: 30
  Transactions flushed: 30
  Transactions rejected: 0
```

#### my docker_daemon.yaml config file
```shell
cat /etc/dd-agent/conf.d/docker_daemon.yaml
init_config:

instances:
    - url: "unix://var/run/docker.sock"
      new_tag_names: true
```

#### dd-agent user is already member of docker group
```shell
id dd-agent 
uid=107(dd-agent) gid=112(dd-agent) groups=112(dd-agent),998(docker)
```

#### and can access to docker socket
```shell
sudo -u dd-agent docker ps
sudo: unable to resolve host prod-sentry2
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
f3fd816cd53f        redis:latest        "docker-entrypoint.sh"   26 minutes ago      Up 12 minutes       6379/tcp            sentry-redis
```

**Comment by adilr00t** [comment] 2016-09-14 19:18
ok fixed by adding `GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"` to `/etc/default/grub` 

update grub `sudo update-grub`

and reboot `sudo shutdown -r now`
