### ISSUE TITLE
Agent doesn't restart after crash due to lack of disk space.

### ISSUE THREAD

**Issue by MiguelMoll** [DataDog/dd-agent#2149] opened 2015-12-15 22:52 UTC
With my limited initial investigation, it seems the forwarder will crash if there is no disk space left while its trying to write.
```
2015-12-14 15:12:20 EST | INFO | dd.forwarder | transaction(transaction.py:158) | No transaction to flush during flush #520
2015-12-14 15:12:20 EST | ERROR | dd.forwarder | checks.check_status(check_status.py:140) | Error persisting status
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/check_status.py", line 138, in persist
    f.close()
IOError: [Errno 28] No space left on device
```

This will leave the agent in a funky state where the collector isn't running. Manual restart is necessary at this point.
```
# /etc/init.d/datadog-agent status
datadog-agent:collector          FATAL     Exited too quickly (process log may have details)
datadog-agent:dogstatsd          RUNNING   pid 130040, uptime 1:55:49
datadog-agent:forwarder          RUNNING   pid 130041, uptime 1:55:49
datadog-agent:jmxfetch           EXITED    Dec 15 03:14 PM
Datadog Agent (supervisor) is NOT running all child processes
```
Not entirely sure if the above `status` is from before or after a supervisord restart. If one even took place.

I can definitely dig into this further. Wondering if this is known or if any work has been any done before I dive in.

Agent v 5.6.3
Ubuntu 14.04

UPDATE: Mistakenly added some information that I thought was related to disk space when it actually wasn't. It was memory related.

**Comment by remh** [comment] 2015-12-17 22:49
Thanks a lot @MiguelMoll we will have a look.

**Comment by olivielpeau** [comment] 2016-04-29 22:15
The merge window for 5.8 is closing and we haven't been able to look at this issue in details yet unfortunately. Moving it back to Triage.

Thanks again @MiguelMoll for reporting the issue, we'll have a close look soon.

**Comment by remh** [comment] 2016-05-02 21:21
Looks like the issue was actually caused by being out of memory. Closing. Thanks for the feedback @MiguelMoll

**Closed by remh** 2016-05-02 21:21 UTC
Labels: core

**Comment by MiguelMoll** [comment] 2016-05-02 21:23
Ha that pesky misleading Python error. Glad to here the news though. Thanks!
