### ISSUE TITLE
agent forwarder doesn't recover after host experiences network issues

### ISSUE THREAD

**Issue by celenechang** [DataDog/dd-agent#1212] opened 2014-11-20 21:06 UTC
when an instance has network issues, the agent forwarder can't submit metrics to datadog's servers (as expected). however, when the instance recovers the forwarder doesn't seem to exit a bad state, requiring agent restart to submit metrics again.

case: 18129

**Comment by remh** [comment] 2016-01-05 22:50
Closing this issue. As we can't reproduce the issue. I was able to recover from a 800 payloads queue without a blip.

**Closed by remh** 2016-01-05 22:50 UTC

**Comment by anroots** [comment] 2016-08-04 08:53
@remh, it's possible that this issue still exists.

I'm running `datadog/docker-dd-agent:11.2.585` on Openshift 3 (Kubernetes). Ever since initial deployment I've been having trouble with the forwarder "stalling" after some time of flawless running. The Docker container with Datadog stays running without restart, but Datadog is no longer receiving telemetry from that host/container.

Upon inspection, the `info` command shows that the forwarder has not sent data to Datadog for quite some time.
```bash
root@redacted:/# /etc/init.d/datadog-agent info
===================
Collector (v 5.8.5)
===================

  Status date: 2016-08-04 08:37:22 (23s ago)
  Pid: 15
  Platform: Linux-3.10.0-327.22.2.el7.x86_64-x86_64-with-debian-8.5
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log

  Clocks
  ======
  
    NTP offset: 0.0045 s
    System UTC time: 2016-08-04 08:37:46.954211
  
  Paths
  =====
  
    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d
  
  Hostnames
  =========
  
    socket-hostname: redacted
    hostname: redacted
    socket-fqdn: redacted
  
  Checks
  ======
  
     haproxy
    -------
      - instance #0 [OK]
      - Collected 1161 metrics, 0 events & 63 service checks
  
    http_check
    ----------
      - instance #0 [OK]
      - instance #1 [OK]
      - instance #2 [OK]
      - instance #3 [OK]
      - instance #4 [OK]
      - instance #5 [OK]
      - instance #6 [OK]
      - instance #7 [OK]
      - instance #8 [OK]
      - instance #9 [OK]
      - instance #10 [OK]
      - instance #11 [OK]
      - instance #12 [OK]
      - Collected 13 metrics, 0 events & 27 service checks
  
  
  Emitters
  ========
  
    - http_emitter [OK]

===================
Dogstatsd (v 5.8.5)
===================

  Status date: 2016-08-04 08:37:37 (10s ago)
  Pid: 12
  Platform: Linux-3.10.0-327.22.2.el7.x86_64-x86_64-with-debian-8.5
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log

  Flush count: 7321
  Packet Count: 0
  Packets per second: 0.0
  Metric count: 1
  Event count: 0
  Service check count: 0

===================
Forwarder (v 5.8.5)
===================

  Status date: 2016-08-04 07:05:15 (5554s ago)
  Pid: 14
  Platform: Linux-3.10.0-327.22.2.el7.x86_64-x86_64-with-debian-8.5
  Python Version: 2.7.12, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log

  Queue Size: 5743320 bytes
  Queue Length: 1831
  Flush Count: 73
  Transactions received: 8638
  Transactions flushed: 6807
  Transactions rejected: 0
```

However, supervisord does not restart the forwarder and both the `info` and `status` commands exit with a status code of `0`.

```bash
root@redacted:/# echo $?
0
root@redacted:/# /etc/init.d/datadog-agent status
Datadog Agent (supervisor) is running all child processes
root@redacted:/# echo $?
0
```

I have defined a Openshift health check for the container, hoping that the container would be restarted by the scheduler on such cases, but because `info` and `status` exit with a `0`, it won't apply.

```yaml
livenessProbe:
  exec:
    command: [/etc/init.d/datadog-agent, info]
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 60
  successThreshold: 1
  failureThreshold: 2
```

The forwarder log shows that it got a timeout at some point and did not proceed.

```bash
root@redacted:/# tail /var/log/datadog/forwarder.log      
2016-08-03 10:56:56 UTC | INFO | dd.forwarder | transaction(transaction.py:156) | Flushing 1 transaction during flush #4
2016-08-03 10:57:00 UTC | INFO | dd.forwarder | transaction(transaction.py:164) | No transaction to flush during flush #5
2016-08-03 10:57:00 UTC | INFO | dd.forwarder | transaction(transaction.py:169) | First flushes done, next flushes will be logged every 20 flushes.
2016-08-03 10:57:42 UTC | INFO | dd.forwarder | transaction(transaction.py:156) | Flushing 1 transaction during flush #20
2016-08-03 10:58:46 UTC | INFO | dd.forwarder | transaction(transaction.py:156) | Flushing 1 transaction during flush #40
2016-08-03 11:57:30 UTC | INFO | dd.forwarder | transaction(transaction.py:156) | Flushing 86 transactions during flush #60
2016-08-03 12:48:15 UTC | ERROR | dd.forwarder | forwarder(ddagent.py:275) | Response: HTTPResponse(_body=None,buffer=None,code=599,effective_url='https://5-8-5-app.agent.datadoghq.com/intake/?api_key=*************************xxxxx',error=HTTPError('HTTP 599: Timeout',),headers={},reason='Unknown',request=<tornado.httpclient.HTTPRequest object at 0x7f18932a8750>,request_time=25.19198203086853,time_info={})
2016-08-03 12:48:15 UTC | WARNING | dd.forwarder | transaction(transaction.py:220) | Transaction 578 in error (1 error), it will be replayed after 2016-08-03 12:48:35
2016-08-03 15:26:56 UTC | ERROR | dd.forwarder | forwarder(ddagent.py:275) | Response: HTTPResponse(_body=None,buffer=None,code=599,effective_url='https://5-8-5-app.agent.datadoghq.com/api/v1/series/?api_key=*************************xxxxx',error=HTTPError('HTTP 599: Timeout',),headers={},reason='Unknown',request=<tornado.httpclient.HTTPRequest object at 0x7f18933152d0>,request_time=47.10162401199341,time_info={})
2016-08-03 15:26:56 UTC | WARNING | dd.forwarder | transaction(transaction.py:220) | Transaction 1476 in error (1 error), it will be replayed after 2016-08-03 15:27:16
root@redacted:/# date
Thu Aug  4 08:42:39 UTC 2016
```

Probably related with https://github.com/DataDog/dd-agent/issues/1004

**Comment by kangman** [comment] 2018-02-23 17:04
@anroots did you get a resolution to this?

**Comment by anroots** [comment] 2018-02-24 07:55
Unknown, I stopped running Datadog on OS3/Kubernetes.

**Comment by htmldrum** [comment] 2018-06-02 01:00
Hi all.
Am seeing this intermittently on a single server in an auto scaling group. Have disabled alerting on host for now to attempt to resolve. Attempted fix by increasing `forwarder_timeout` in /etc/dd-agent/conf.d to 30s, no effect. Details below.

IO, CPU, MEM are low. 
Other external sidecars are resolving and operating as usual.

```
====================
Collector (v 5.24.0)
====================

  Status date: 2018-06-02 10:43:27 (7s ago)
  Pid: 32157
  Platform: Linux-3.13.0-149-generic-x86_64-with-Ubuntu-14.04-trusty
  Python Version: 2.7.14, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log, syslog:/dev/log

  Clocks
  ======

    NTP offset: Unknown (No response received from 2.datadog.pool.ntp.org.)
    System UTC time: 2018-06-02 00:43:36.265356

  Paths
  =====

    conf.d: /etc/dd-agent/conf.d
    checks.d: Not found

  Hostnames
  =========

    ec2-hostname: [REDACTED]
    local-ipv4: 10.200.54.191
    socket-hostname: [REDACTED]
    hostname: [REDACTED]
    local-hostname: [REDACTED]
    instance-id: i-0d6685770c625be7a
    socket-fqdn: [REDACTED]

  Checks
  ======

    ntp (1.2.0)
    -----------
      - Collected 0 metrics, 0 events & 0 service checks

    disk (1.2.0)
    ------------
      - instance #0 [OK]
      - Collected 26 metrics, 0 events & 0 service checks

    network (1.5.0)
    ---------------
      - instance #0 [OK]
      - Collected 20 metrics, 0 events & 0 service checks


  Emitters
  ========

    - http_emitter [OK]

====================
Dogstatsd (v 5.24.0)
====================

  Status date: 2018-06-02 10:43:27 (8s ago)
  Pid: 32154
  Platform: Linux-3.13.0-149-generic-x86_64-with-Ubuntu-14.04-trusty
  Python Version: 2.7.14, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log, syslog:/dev/log

  Flush count: 43
  Packet Count: 250
  Packets per second: 0.3
  Metric count: 21
  Event count: 0
  Service check count: 0

====================
Forwarder (v 5.24.0)
====================

  Status date: 2018-06-02 10:43:17 (19s ago)
  Pid: 32153
  Platform: Linux-3.13.0-149-generic-x86_64-with-Ubuntu-14.04-trusty
  Python Version: 2.7.14, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log, syslog:/dev/log

  Queue Size: 159839 bytes
  Queue Length: 111
  Flush Count: 22
  Transactions received: 111
  Transactions flushed: 0
  Transactions rejected: 0
  API Key Status: API Key is valid


======================
Trace Agent (v 5.24.0)
======================

  Pid: 32152
  Uptime: 439 seconds
  Mem alloc: 2073488 bytes

  Hostname: [REDACTED]
  Receiver: localhost:8126
  API Endpoint: https://trace.agent.datadoghq.com

  --- Receiver stats (1 min) ---


  --- Writer stats (1 min) ---

  Traces: 0 payloads, 0 traces, 0 bytes
  Stats: 0 payloads, 0 stats buckets, 0 bytes
  Services: 0 payloads, 0 services, 0 bytes```


```$ tail -f /var/log/datadog/forwarder.log
2018-06-02 10:32:30 AEST | WARNING | dd.forwarder | transaction(transaction.py:212) | Flush 10 is taking more than 10s, stopping it
2018-06-02 10:32:50 AEST | ERROR | dd.forwarder | forwarder(ddagent.py:282) | Response: HTTPResponse(_body=None,buffer=None,code=599,effective_url='https://5-24-0-app.agent.datadoghq.com/api/v1/series/?api_key=*************************e8bfb',error=HTTPError('HTTP 599: Timeout',),headers={},reason='Unknown',request=<tornado.httpclient.HTTPRequest object at 0x7f6f8015bf50>,request_time=20.00029683113098,time_info={})
2018-06-02 10:32:50 AEST | WARNING | dd.forwarder | transaction(transaction.py:268) | Transaction 49 in error (1 error), it will be replayed after 2018-06-02 00:33:10
2018-06-02 10:32:50 AEST | WARNING | dd.forwarder | transaction(transaction.py:212) | Flush 11 is taking more than 10s, stopping it
2018-06-02 10:33:10 AEST | ERROR | dd.forwarder | forwarder(ddagent.py:282) | Response: HTTPResponse(_body=None,buffer=None,code=599,effective_url='https://5-24-0-app.agent.datadoghq.com/api/v1/series/?api_key=*************************e8bfb',error=HTTPError('HTTP 599: Timeout',),headers={},reason='Unknown',request=<tornado.httpclient.HTTPRequest object at 0x7f6f80398bd0>,request_time=20.00031805038452,time_info={})
2018-06-02 10:33:10 AEST | WARNING | dd.forwarder | transaction(transaction.py:268) | Transaction 54 in error (1 error), it will be replayed after 2018-06-02 00:33:30
2018-06-02 10:33:10 AEST | WARNING | dd.forwarder | transaction(transaction.py:212) | Flush 12 is taking more than 10s, stopping it
2018-06-02 10:33:30 AEST | ERROR | dd.forwarder | forwarder(ddagent.py:282) | Response: HTTPResponse(_body=None,buffer=None,code=599,effective_url='https://5-24-0-app.agent.datadoghq.com/api/v1/series/?api_key=*************************e8bfb',error=HTTPError('HTTP 599: Timeout',),headers={},reason='Unknown',request=<tornado.httpclient.HTTPRequest object at 0x7f6f7fccf6d0>,request_time=20.00053095817566,time_info={})
2018-06-02 10:33:30 AEST | WARNING | dd.forwarder | transaction(transaction.py:268) | Transaction 59 in error (1 error), it will be replayed after 2018-06-02 00:33:50
2018-06-02 10:33:30 AEST | WARNING | dd.forwarder | transaction(transaction.py:212) | Flush 13 is taking more than 10s, stopping it
2018-06-02 10:33:51 AEST | ERROR | dd.forwarder | forwarder(ddagent.py:282) | Response: HTTPResponse(_body=None,buffer=None,code=599,effective_url='https://5-24-0-app.agent.datadoghq.com/api/v1/series/?api_key=*************************e8bfb',error=HTTPError('HTTP 599: Timeout',),headers={},reason='Unknown',request=<tornado.httpclient.HTTPRequest object at 0x7f6f7fccffd0>,request_time=20.000298976898193,time_info={})
2018-06-02 10:33:51 AEST | WARNING | dd.forwarder | transaction(transaction.py:268) | Transaction 64 in error (1 error), it will be replayed after 2018-06-02 00:34:11
2018-06-02 10:33:51 AEST | WARNING | dd.forwarder | transaction(transaction.py:212) | Flush 14 is taking more than 10s, stopping it
2018-06-02 10:34:11 AEST | ERROR | dd.forwarder | forwarder(ddagent.py:282) | Response: HTTPResponse(_body=None,buffer=None,code=599,effective_url='https://5-24-0-app.agent.datadoghq.com/api/v1/series/?api_key=*************************e8bfb',error=HTTPError('HTTP 599: Timeout',),headers={},reason='Unknown',request=<tornado.httpclient.HTTPRequest object at 0x7f6f7fce92d0>,request_time=20.000684022903442,time_info={})
2018-06-02 10:34:11 AEST | WARNING | dd.forwarder | transaction(transaction.py:268) | Transaction 69 in error (1 error), it will be replayed after 2018-06-02 00:34:31
2018-06-02 10:34:11 AEST | WARNING | dd.forwarder | transaction(transaction.py:212) | Flush 15 is taking more than 10s, stopping it
2018-06-02 10:34:31 AEST | ERROR | dd.forwarder | forwarder(ddagent.py:282) | Response: HTTPResponse(_body=None,buffer=None,code=599,effective_url='https://5-24-0-app.agent.datadoghq.com/api/v1/series/?api_key=*************************e8bfb',error=HTTPError('HTTP 599: Timeout',),headers={},reason='Unknown',request=<tornado.httpclient.HTTPRequest object at 0x7f6f7fce9790>,request_time=20.000505924224854,time_info={})
2018-06-02 10:34:31 AEST | WARNING | dd.forwarder | transaction(transaction.py:268) | Transaction 74 in error (1 error), it will be replayed after 2018-06-02 00:34:51
2018-06-02 10:34:31 AEST | WARNING | dd.forwarder | transaction(transaction.py:212) | Flush 16 is taking more than 10s, stopping it```

**Comment by htmldrum** [comment] 2018-06-18 04:51
I managed to get the forwarder working over a proxy connection by manually configuring the proxy configuration in `/etc/dd-agent/datadog.conf`. Previously, I was able to the `http_proxy` header to do this.

Please consider my issue resolved. Thank you.
