### ISSUE TITLE
OSX agent failing after install

### ISSUE THREAD

**Issue by clofresh** [DataDog/dd-agent#2307] opened 2016-03-01 03:34 UTC
Ran the standard OS X agent install:

```
DD_API_KEY=<key> bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/osx/install.sh)"
```

And it says it installed correctly

```
Your Agent is running and functioning properly. It will continue to run in the
background and submit metrics to Datadog.
```

but my signup wasn't going through. I checked /var/log/datadog/collector.log and saw a crashing error:

```
2016-02-29 22:29:47 EST | ERROR | dd.collector | checks.collector(debug.py:25) | Uncaught exception while running run
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/utils/debug.py", line 22, in wrapper
    result = func(*args, **kwargs)
  File "/opt/datadog-agent/agent/checks/collector.py", line 481, in run
    self._populate_payload_metadata(payload, check_statuses, start_event)
  File "/opt/datadog-agent/agent/checks/collector.py", line 645, in _populate_payload_metadata
    raise e
OSError: [Errno 20] Not a directory
2016-02-29 22:29:47 EST | ERROR | dd.collector | collector(agent.py:391) | Uncaught error running the Agent
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/agent.py", line 387, in <module>
    sys.exit(main())
  File "/opt/datadog-agent/agent/agent.py", line 331, in main
    agent.start(foreground=True)
  File "/opt/datadog-agent/agent/daemon.py", line 178, in start
    self.run()
  File "/opt/datadog-agent/agent/agent.py", line 182, in run
    configs_reloaded=self.configs_reloaded)
  File "/opt/datadog-agent/agent/utils/debug.py", line 22, in wrapper
    result = func(*args, **kwargs)
  File "/opt/datadog-agent/agent/checks/collector.py", line 481, in run
    self._populate_payload_metadata(payload, check_statuses, start_event)
  File "/opt/datadog-agent/agent/checks/collector.py", line 645, in _populate_payload_metadata
    raise e
OSError: [Errno 20] Not a directory
```

Workaround is to hack this line with the absolute path `/opt/datadog-agent/bin/gohai`: https://github.com/DataDog/dd-agent/blob/master/checks/collector.py#L638

Running OS X El Capitan 10.11.2. Not sure if it makes a difference but I'm also using bash 4.3.42 from homebrew .

**Comment by olivielpeau** [comment] 2016-03-01 04:44
Weird error, I can't reproduce on a fresh install of the agent on my OS X (10.11.1).

AFAIK even in cases where `gohai` can't be found the `OSError` should be `[Errno 2] No such file or directory`, which is handled gracefully by the collector.

**Comment by clofresh** [comment] 2016-03-01 14:29
Tried again with a different Mac and it worked. Maybe I had an old agent install on there or something.

**Comment by olivielpeau** [comment] 2016-03-01 20:10
Merged #2309 to avoid having the whole collector fail if this issue happens again (Gohai should never prevent the collector from sending payloads).

Closing this as I don't think it's worth investigating more. Thanks @clofresh!

**Closed by olivielpeau** 2016-03-01 20:10 UTC

**Comment by maxim-filkov** [comment] 2017-04-10 15:33
I'm having similar issue right now with OS X El Capitan Version 10.11.2.

```
Collector (v 5.12.3)
====================

  Status date: 2017-04-10 15:30:13 (2s ago)
  Pid: 21
  Platform: Linux-4.9.13-moby-x86_64-with
  Python Version: 2.7.12, 64bit

tail -f /opt/datadog-agent/logs/collector.log
2017-04-10 15:22:12  | INFO | dd.collector | checks.collector(collector.py:793) | gohai file not found
2017-04-10 15:22:12  | ERROR | dd.collector | checks.varnish(__init__.py:805) | Check 'varnish' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 788, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/../integrations/varnish/check.py", line 104, in check
    output, _, _ = get_subprocess_output(cmd, self.log)
  File "/opt/datadog-agent/agent/utils/subprocess_output.py", line 27, in get_subprocess_output
    proc = subprocess.Popen(command, stdout=stdout_f, stderr=stderr_f)
  File "/opt/datadog-agent/agent/utils/subprocess_output.py", line 54, in wrapper
    return func(*params, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
```

**Comment by olivielpeau** [comment] 2017-04-10 16:00
@maxim-filkov I think your issue is not related to the present issue, it looks like your issue is limited to the varnish check.

Could you send a [flare](https://github.com/DataDog/dd-agent/wiki/Send-logs-to-support-using-flare) to our support team so that we can troubleshoot your issue? Feel free to provide detailed information on your environment and setup.

Thanks!

**Comment by maxim-filkov** [comment] 2017-04-11 09:23
@olivielpeau, thanks for prompt reply, I have still submitted another ticket [here](https://github.com/DataDog/dd-agent/issues/3302). Let me know if more info is needed from my side. Thanks!
