### ISSUE TITLE
is one JVM is blocked none of the monitors from the same agent will report

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/dd-agent#1753] opened 2015-07-08 10:44 UTC
Monitor several instances of tomcat (tomcat.yml) using dd-agent 5.4.2 and we discovered that if one of these instances is blocked the monitoring is stopped for all instances.

This can be easily seen on our monitoring graphs because until the instance was fully restarted the data is missing for all of them.

This is a serious issue.

**Comment by yannmh** [comment] 2015-07-10 14:36
Thanks for reporting @ssbarnea. This is indeed quite a serious issue. 
To help our investigations, would you be able to forward us more details through support please ? In particular, your tomcat YAML configuration file as well as your JMX logs during the outage (if you still have it). 
Also, could you let us know what you do mean by a 'blocked' instance ? Is the instance itself stuck or simply down/unreachable ? Thanks

**Comment by yannmh** [comment] 2015-07-27 21:36
I haven't heard back from you @ssbarnea. Are you still affected by the issue ?

**Comment by yannmh** [comment] 2015-08-03 20:03
We were not able to reproduce, and have no extra information.

I am closing the ticket, but please feel free to re-open it with more inforation if you are still affected. Thank you

**Closed by yannmh** 2015-08-03 20:03 UTC
Labels: bugfix
