### ISSUE TITLE
Can't stop datadog-agent

### ISSUE THREAD

**Issue by AntoCard** [DataDog/dd-agent#1972] opened 2015-10-09 10:16 UTC
Ubuntu 14.10 in AWS

`service datadog-agent stop/restart` does not cause datadog to restart. 

Using `/opt/datadog-agent/bin/supervisorctl -c /etc/dd-agent/supervisor.conf restart datadog-agent:*` does work as expected.

**Comment by hkaj** [comment] 2015-10-12 13:20
Hi @AntoCard, thank you for reaching out.
We can't reproduce this issue on a fresh install. Could you provide some logs to help us investigate please?
supervisor logs would be useful (`/var/log/datadog/supervisord.log`), as well as the output of `service datadog-agent info`.
Thanks!

**Comment by AntoCard** [comment] 2015-10-13 10:12
Hello @hkaj thanks for the reply.

Please find below `service datadog-agent info` output

```===================
Collector (v 5.4.3)
===================

  Status date: 2015-10-13 10:02:00 (19s ago)
  Pid: 44672
  Platform: Linux-3.16.0-44-generic-x86_64-with-debian-jessie-sid
  Python Version: 2.7.10
  Logs: <stderr>, /var/log/datadog/collector.log, syslog:/dev/log

  Clocks
  ======
  
    NTP offset: 0.002 s
    System UTC time: 2015-10-13 10:02:19.768990
  
  Paths
  =====
  
    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d
  
  Hostnames
  =========
  
    ec2-hostname: ip-X-X-X-X.eu-west-1.compute.internal
    local-ipv4: X.X.X.X
    hostname: ip-X-X-X-X.eu-west-1.compute.internal
    socket-hostname: ip-X-X-X-X
    local-hostname: ip-X-X-X-X.eu-west-1.compute.internal
    instance-id: i-blablabla
    socket-fqdn: ip-X-X-X-X
  
  Checks
  ======
  
    network
    -------
      - instance #0 [OK]
      - Collected 141 metrics, 0 events & 1 service check
  
    mesos_slave
    -----------
      - instance #0 [ERROR]: "'cluster'"
      - Collected 0 metrics, 0 events & 1 service check
    ntp
    ---
      - Collected 0 metrics, 0 events & 1 service check
  
    consul
    ------
      - instance #0 [OK]
      - Collected 1 metric, 0 events & 1 service check
  
    docker
    ------
      - instance #0 [WARNING]
          Warning: Failed to count Docker images. Exception: timed out
      - Collected 111 metrics, 1 event & 2 service checks
  
    disk
    ----
      - instance #0 [OK]
      - Collected 24 metrics, 0 events & 1 service check
  
  
  Emitters
  ========
  
    - http_emitter [OK]

===================
Dogstatsd (v 5.4.3)
===================

  Status date: 2015-10-13 10:02:15 (4s ago)
  Pid: 44583
  Platform: Linux-3.16.0-44-generic-x86_64-with-debian-jessie-sid
  Python Version: 2.7.10
  Logs: <stderr>, /var/log/datadog/dogstatsd.log, syslog:/dev/log

  Flush count: 32220
  Packet Count: 63691150
  Packets per second: 188.3
  Metric count: 273
  Event count: 0
===================
Forwarder (v 5.4.3)
===================

  Status date: 2015-10-13 10:02:18 (1s ago)
  Pid: 44584
  Platform: Linux-3.16.0-44-generic-x86_64-with-debian-jessie-sid
  Python Version: 2.7.10
  Logs: <stderr>, /var/log/datadog/forwarder.log, syslog:/dev/log

  Queue Size: 0 bytes
  Queue Length: 0
  Flush Count: 104891
  Transactions received: 44584
  Transactions flushed: 44584
  ```
And `/var/log/datadog/supervisord.log`, not seeing anything there when I use `service datadog-agent restart`

```
2015-09-03 12:44:34,306 CRIT Supervisor running as root (no user in config file)
2015-09-03 12:44:34,313 INFO RPC interface 'supervisor' initialized
2015-09-03 12:44:34,313 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2015-09-03 12:44:34,314 INFO daemonizing the supervisord process
2015-09-03 12:44:34,314 INFO supervisord started with pid 31171
2015-09-03 12:44:34,401 INFO spawned: 'dogstatsd' with pid 31175
2015-09-03 12:44:34,402 INFO spawned: 'forwarder' with pid 31176
2015-09-03 12:44:34,403 INFO spawned: 'collector' with pid 31177
2015-09-03 12:44:34,404 INFO spawned: 'jmxfetch' with pid 31178
2015-09-03 12:44:37,640 INFO success: jmxfetch entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2015-09-03 12:44:38,644 INFO exited: jmxfetch (exit status 0; expected)
2015-09-03 12:44:39,611 INFO success: dogstatsd entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2015-09-03 12:44:39,631 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2015-09-03 12:44:39,631 INFO success: collector entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2015-09-03 12:44:40,893 WARN received SIGTERM indicating exit request
2015-09-03 12:44:40,894 INFO waiting for dogstatsd, forwarder, collector to die
2015-09-03 12:44:40,907 INFO stopped: forwarder (exit status 0)
2015-09-03 12:44:40,911 INFO stopped: collector (exit status 0)
2015-09-03 12:44:40,945 INFO stopped: dogstatsd (exit status 0)
2015-09-03 12:44:41,301 CRIT Supervisor running as root (no user in config file)
2015-09-03 12:44:41,308 INFO RPC interface 'supervisor' initialized
2015-09-03 12:44:41,308 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2015-09-03 12:44:41,309 INFO daemonizing the supervisord process
2015-09-03 12:44:41,309 INFO supervisord started with pid 32024
2015-09-03 12:44:41,393 INFO spawned: 'dogstatsd' with pid 32028
2015-09-03 12:44:41,394 INFO spawned: 'forwarder' with pid 32029
2015-09-03 12:44:41,396 INFO spawned: 'collector' with pid 32030
2015-09-03 12:44:41,397 INFO spawned: 'jmxfetch' with pid 32031
2015-09-03 12:44:44,611 INFO success: jmxfetch entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2015-09-03 12:44:45,621 INFO exited: jmxfetch (exit status 0; expected)
2015-09-03 12:44:46,699 INFO success: dogstatsd entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2015-09-03 12:44:46,699 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2015-09-03 12:44:46,700 INFO success: collector entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2015-09-03 12:44:49,031 WARN received SIGTERM indicating exit request
2015-09-03 12:44:49,031 INFO waiting for dogstatsd, forwarder, collector to die
2015-09-03 12:44:49,048 INFO stopped: collector (exit status 0)
2015-09-03 12:44:49,049 INFO stopped: forwarder (exit status 0)
2015-09-03 12:44:49,105 INFO stopped: dogstatsd (exit status 0)
2015-09-03 13:19:03,308 CRIT Supervisor running as root (no user in config file)
2015-09-03 13:19:03,512 INFO RPC interface 'supervisor' initialized
2015-09-03 13:19:03,512 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2015-09-03 13:19:03,513 INFO daemonizing the supervisord process
2015-09-03 13:19:03,514 INFO supervisord started with pid 2401
2015-09-03 13:19:03,583 INFO spawned: 'dogstatsd' with pid 2405
2015-09-03 13:19:03,584 INFO spawned: 'forwarder' with pid 2406
2015-09-03 13:19:03,585 INFO spawned: 'collector' with pid 2407
2015-09-03 13:19:03,585 INFO spawned: 'jmxfetch' with pid 2408
2015-09-03 13:19:04,578 CRIT Supervisor running as root (no user in config file)
2015-09-03 13:19:06,737 INFO success: jmxfetch entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2015-09-03 13:19:07,704 INFO exited: jmxfetch (exit status 0; expected)
2015-09-03 13:19:08,842 INFO success: dogstatsd entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2015-09-03 13:19:08,914 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2015-09-03 13:19:08,914 INFO success: collector entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2015-10-09 16:21:40,453 INFO stopped: forwarder (exit status 0)
2015-10-09 16:21:40,490 INFO stopped: dogstatsd (exit status 0)
2015-10-09 16:21:42,959 INFO stopped: collector (exit status 0)
2015-10-09 16:21:42,966 INFO spawned: 'dogstatsd' with pid 44583
2015-10-09 16:21:42,968 INFO spawned: 'forwarder' with pid 44584
2015-10-09 16:21:43,308 INFO spawned: 'collector' with pid 44672
2015-10-09 16:21:43,571 INFO spawned: 'jmxfetch' with pid 44679
2015-10-09 16:21:46,641 INFO success: jmxfetch entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2015-10-09 16:21:47,751 INFO exited: jmxfetch (exit status 0; expected)
2015-10-09 16:21:48,092 INFO success: dogstatsd entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2015-10-09 16:21:48,093 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2015-10-09 16:21:48,317 INFO success: collector entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
```

**Comment by hkaj** [comment] 2015-10-23 12:50
Hi @AntoCard ,
```
2015-09-03 12:44:40,893 WARN received SIGTERM indicating exit request
2015-09-03 12:44:40,894 INFO waiting for dogstatsd, forwarder, collector to die
2015-09-03 12:44:40,907 INFO stopped: forwarder (exit status 0)
2015-09-03 12:44:40,911 INFO stopped: collector (exit status 0)
2015-09-03 12:44:40,945 INFO stopped: dogstatsd (exit status 0)
2015-09-03 12:44:41,301 CRIT Supervisor running as root (no user in config file)
2015-09-03 12:44:41,308 INFO RPC interface 'supervisor' initialized
2015-09-03 12:44:41,308 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2015-09-03 12:44:41,309 INFO daemonizing the supervisord process
2015-09-03 12:44:41,309 INFO supervisord started with pid 32024
2015-09-03 12:44:41,393 INFO spawned: 'dogstatsd' with pid 32028
2015-09-03 12:44:41,394 INFO spawned: 'forwarder' with pid 32029
2015-09-03 12:44:41,396 INFO spawned: 'collector' with pid 32030
2015-09-03 12:44:41,397 INFO spawned: 'jmxfetch' with pid 32031
2015-09-03 12:44:44,611 INFO success: jmxfetch entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2015-09-03 12:44:45,621 INFO exited: jmxfetch (exit status 0; expected)
2015-09-03 12:44:46,699 INFO success: dogstatsd entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2015-09-03 12:44:46,699 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2015-09-03 12:44:46,700 INFO success: collector entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
```
and 
```
2015-09-03 12:44:49,031 WARN received SIGTERM indicating exit request
2015-09-03 12:44:49,031 INFO waiting for dogstatsd, forwarder, collector to die
2015-09-03 12:44:49,048 INFO stopped: collector (exit status 0)
2015-09-03 12:44:49,049 INFO stopped: forwarder (exit status 0)
2015-09-03 12:44:49,105 INFO stopped: dogstatsd (exit status 0)
2015-09-03 13:19:03,308 CRIT Supervisor running as root (no user in config file)
2015-09-03 13:19:03,512 INFO RPC interface 'supervisor' initialized
2015-09-03 13:19:03,512 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2015-09-03 13:19:03,513 INFO daemonizing the supervisord process
2015-09-03 13:19:03,514 INFO supervisord started with pid 2401
2015-09-03 13:19:03,583 INFO spawned: 'dogstatsd' with pid 2405
2015-09-03 13:19:03,584 INFO spawned: 'forwarder' with pid 2406
2015-09-03 13:19:03,585 INFO spawned: 'collector' with pid 2407
2015-09-03 13:19:03,585 INFO spawned: 'jmxfetch' with pid 2408
2015-09-03 13:19:04,578 CRIT Supervisor running as root (no user in config file)
2015-09-03 13:19:06,737 INFO success: jmxfetch entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2015-09-03 13:19:07,704 INFO exited: jmxfetch (exit status 0; expected)
2015-09-03 13:19:08,842 INFO success: dogstatsd entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2015-09-03 13:19:08,914 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2015-09-03 13:19:08,914 INFO success: collector entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
```

look very much like successful restarts. Are they not due to a `service datadog-agent restart` command?

Also when you run this command you should see this in the shell:
![image](http://g.recordit.co/B0GCp2vXDg.gif)

Is it not the case?

To see if the command has an impact you can run `tail -f /var/log/datadog/supervisord.log` in a shell and `sudo service datadog-agent restart` and see what new is appended to the log file.

Let me know if that helps.

**Comment by AntoCard** [comment] 2015-10-23 13:02
Hi @hkaj 

What you seen in those logs is part of the way we create our AMI. We use Ansible to provision it and then bundle the AMI. The problem happens when you create an instance using that AMI. Sorry if I wasn't clear about that.

Thanks

**Comment by remh** [comment] 2016-01-05 20:58
@AntoCard is it still happening with the latest version of the agent ? If so can you reach out to support with a flare please ? https://github.com/DataDog/dd-agent/wiki/Send-logs-to-support-using-flare

I'm closing for now, but i will reopen if you reconfirm that it's still happening.
Thanks for the feedback!

**Closed by remh** 2016-01-05 20:58 UTC

**Comment by AntoCard** [comment] 2016-01-06 09:50
@remh we downgraded to Ubuntu 14.04 for unrelated reasons and the problem has not happened again. Unsure what caused it.

Thanks!

**Comment by remh** [comment] 2016-01-06 15:20
Thanks for the reply!
