### ISSUE TITLE
collector bails out if can't connect to expvar endpoint

### ISSUE THREAD

**Issue by Dieterbe** [DataDog/dd-agent#1893] opened 2015-09-04 07:19 UTC
```
2015-09-04 07:13:35 UTC | ERROR | dd.collector | checks.go_expvar(__init__.py:678) | Check 'go_expvar' instance #1 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/go_expvar.py", line 98, in check
    data, tags, metrics, max_metrics, url = self._load(instance)
  File "/opt/datadog-agent/agent/checks.d/go_expvar.py", line 71, in _load
    data = self._get_data(url)
  File "/opt/datadog-agent/agent/checks.d/go_expvar.py", line 60, in _get_data
    r = requests.get(url)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
2015-09-04 07:13:54 UTC | ERROR | dd.collector | checks.go_expvar(__init__.py:678) | Check 'go_expvar' instance #1 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 661, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/go_expvar.py", line 98, in check
    data, tags, metrics, max_metrics, url = self._load(instance)
  File "/opt/datadog-agent/agent/checks.d/go_expvar.py", line 71, in _load
    data = self._get_data(url)
  File "/opt/datadog-agent/agent/checks.d/go_expvar.py", line 60, in _get_data
    r = requests.get(url)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
2015-09-04 07:14:00 UTC | INFO | dd.collector | checks.http_check(network_checks.py:97) | Stopping Thread Pool
2015-09-04 07:14:00 UTC | INFO | dd.collector | collector(agent.py:176) | Exiting. Bye bye.
```

**Comment by Dieterbe** [comment] 2015-09-04 07:20
cc @woodsay

**Comment by remh** [comment] 2015-09-11 19:47
@Dieterbe Thanks for reporting. This is the expected behavior though. Exceptions are raised when checks are failing. 

Would you like the logs to be less spammy ?

**Comment by Dieterbe** [comment] 2015-09-12 16:08
no i don't want the datadog agent to exit when an expvar endpoint is unavailable.
sometimes a configured endpoint is just down but i still want to use the other datadog agent functionality.

**Comment by remh** [comment] 2015-09-14 16:51
@Dieterbe This is unrelated The agent is not exiting because of the go expvar check as all exceptions 

are caught https://github.com/DataDog/dd-agent/blob/master/checks/collector.py#L425-L426

Are you seeing the agent exiting concistently ? 
Can you reach out to our support team with logs at the log level please ? 
I'm closing this issue as it's really unlikely to be related to the go expvar integration.

Thanks for the feedback!

**Closed by remh** 2015-09-14 16:51 UTC
