### ISSUE TITLE
[Windows] Memory leak

### ISSUE THREAD

**Issue by mausch** [DataDog/dd-agent#2648] opened 2016-07-01 11:22 UTC
Been running a ddagent.exe (version 5.7.2.0) instance since 2016-03-29 and it's now using up 1.6GB private bytes / 1.2GB working set.

Looks like a memory leak.

**Comment by olivielpeau** [comment] 2016-07-01 16:01
Hi @mausch, thanks for opening this issue.

Could you give us some more info on your setup, in particular the architecture of the Agent (32-bit or 64-bit), the checks that you're using, and any other info that may prove useful? The usual way to do that is to send a [flare](https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command) to our support team (and specify the architecture of the agent since it's not collected by flare in 5.7.x).

Thanks again!

**Comment by mausch** [comment] 2016-07-05 16:13
64-bit agent.
Checks:
* **NTP** (standard out of the box)
* **disk** (standard out of the box)
* **agent_metrics** (standard out of the box)
* network
* **wmi_check**: classes Win32_PerfRawData_NETFramework_NETCLRLocksAndThreads
 and Win32_Process , filtered and tagged by name

Just sent a flare, case id 57453

**Comment by olivielpeau** [comment] 2016-07-05 17:08
Thanks @mausch, we'll have a look at the flare

**Comment by olivielpeau** [comment] 2016-07-06 12:03
@mausch We were able to reproduce the issue internally, it seems to affect the forwarder of the 64-bit Windows agent only, but the collector is unaffected. Your logs don't show anything that hints at any other issue so I think you're affected by the same memory leak.

While we work at fixing the memory leak, you may want to uninstall the 64-bit agent and install the `5.8.3` 32-bit agent instead. This version of the 32-bit agent allows querying WMI classes from 64-bit processes thanks to a new `provider` option in the wmi_check configuration (see https://github.com/DataDog/dd-agent/blob/5.8.3/conf.d/wmi_check.yaml.example#L20-L22). Let us know if this works for you.

Thanks!

**Comment by mausch** [comment] 2016-07-06 16:52
I've installed 5.8.3 32-bit and set `provider: 64` in each WMI class and now I'm getting this error in the collector log:

```
2016-07-06 16:51:16 Coordinated Universal Time | WARNING | checks.wmi_check(sampler.pyc:468) | Failed to execute WMI query (Select NumberofcurrentlogicalThreads,NumberofcurrentphysicalThreads,Numberofcurrentrecognizedthreads,Name,Timestamp_Sys100NS,Frequency_Sys100NS from Win32_PerfRawData_NETFramework_NETCLRLocksAndThreads WHERE ( Name = 'w3wp' ) OR ( Name LIKE 'Elevate%' ))
Traceback (most recent call last):
  File "checks\libs\wmi\sampler.pyc", line 465, in _query
  File "checks\libs\wmi\sampler.pyc", line 493, in _parse_results
  File "win32com\client\util.pyc", line 84, in next
com_error: (-2147217392, 'OLE error 0x80041010', None, None)
```

**Comment by yannmh** [comment] 2016-07-06 18:44
@mausch, `OLE error 0x80041010` stands for [`WMI Invalid Class`](https://social.technet.microsoft.com/Forums/scriptcenter/en-US/d0e40221-bf73-4f31-a2fd-59966bf7e5df/wmi-invalid-class-0x80041010?forum=ITCG.). In other words, the WMI check seems unable to query the `Win32_PerfRawData_NETFramework_NETCLRLocksAndThreads` WMI class despite the provider being set to `64`.

We'd need some extra information to troubleshoot. Could you follow up on the support ticket with a **DEBUG** `flare` with the new YAML configuration file using `provider: 64` please ? 
Additionally, do you get the same error when `provider` is unset ?

Thank you,

Yann

**Comment by mausch** [comment] 2016-07-07 09:46
Just attached another flare to the same case. Yes I get the same error if `provider` is unset.

**Comment by mausch** [comment] 2016-07-08 14:51
My bad - the server I was installing this version on (a server on the test environment) does not have any .NET performance counters for whatever reason.
I've just installed it on a different server and it's working fine.

**Comment by yannmh** [comment] 2016-07-08 15:48
Glad to hear 😄  

On a side note, we are working on fixing those memory issues on the Windows' Datadog Agent 64-bit.

**Comment by tayl0r** [comment] 2017-07-06 15:19
is this actually still open or is it fixed now?

**Comment by masci** [comment] 2017-07-06 17:28
Closing, the original issue was solved and the latest agent is not leaking.

**Closed by masci** 2017-07-06 17:28 UTC
