### ISSUE TITLE
[core] Memory leak in Windows agent

### ISSUE THREAD

**Issue by mausch** [DataDog/dd-agent#2654] opened 2016-07-05 13:09 UTC
It seems there's a memory leak in v5.7.2 of the Windows agent. Running since 2016-03-29, it's using up 1.7 GB private bytes / 1.5 GB working set. I see similar memory usage on three different servers.

Related: #2364

**Comment by remh** [comment] 2016-07-05 15:27
Thanks @mausch 
This seems like a duplicate of your other issue :) https://github.com/DataDog/dd-agent/issues/2648

Can you provide with the details @olivielpeau asked on the other Github issue please ?

**Closed by remh** 2016-07-05 15:27 UTC

**Comment by mausch** [comment] 2016-07-05 15:55
D'oh, forgot I had already opened that one, sorry!
