### ISSUE TITLE
[gohai] Throwing `panic:runtime` error

### ISSUE THREAD

**Issue by JohnLZeller** [DataDog/dd-agent#2060] opened 2015-11-06 17:19 UTC
When running gohai with agent 5.6.1, it is throwing an error. Here is the traceback:

```
2015-11-06 12:14:58 Eastern Standard Time | DEBUG | checks.collector(subprocess_output.pyc:36) | Error while running gohai\gohai.exe : panic: runtime error: index out of range

goroutine 16 [running]:
runtime.panic(0x514d40, 0x5ddf5c)
	c:/go/src/pkg/runtime/panic.c:279 +0xe9
github.com/DataDog/gohai/windowsutils.WindowsWMICommand(0x5230f0, 0x3, 0x10d24390, 0x5, 0x5, 0x184168, 0x0, 0x0)
	C:/workspace/go/src/github.com/DataDog/gohai/windowsutils/utils.go:57 +0x8f
github.com/DataDog/gohai/cpu.getCpuInfo(0x10d2b6e0, 0x0, 0x0)
	C:/workspace/go/src/github.com/DataDog/gohai/cpu/cpu_windows.go:27 +0xb0
github.com/DataDog/gohai/cpu.(*Cpu).Collect(0x5e07d8, 0x0, 0x0, 0x0, 0x0)
	C:/workspace/go/src/github.com/DataDog/gohai/cpu/cpu.go:12 +0x47
main.Collect(0x10d2b6c0, 0x0, 0x0)
	C:/workspace/go/src/github.com/DataDog/gohai/gohai.go:32 +0xc6
main.main()
	C:/workspace/go/src/github.com/DataDog/gohai/gohai.go:44 +0x24

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
	c:/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
	c:/go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
	c:/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
	c:/go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
	c:/go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
	c:/go/src/pkg/runtime/proc.c:1445

2015-11-06 12:14:58 Eastern Standard Time | WARNING | checks.collector(collector.pyc:641) | GOHAI LOG | panic: runtime error: index out of range

goroutine 16 [running]:
runtime.panic(0x514d40, 0x5ddf5c)
	c:/go/src/pkg/runtime/panic.c:279 +0xe9
github.com/DataDog/gohai/windowsutils.WindowsWMICommand(0x5230f0, 0x3, 0x10d24390, 0x5, 0x5, 0x184168, 0x0, 0x0)
	C:/workspace/go/src/github.com/DataDog/gohai/windowsutils/utils.go:57 +0x8f
github.com/DataDog/gohai/cpu.getCpuInfo(0x10d2b6e0, 0x0, 0x0)
	C:/workspace/go/src/github.com/DataDog/gohai/cpu/cpu_windows.go:27 +0xb0
github.com/DataDog/gohai/cpu.(*Cpu).Collect(0x5e07d8, 0x0, 0x0, 0x0, 0x0)
	C:/workspace/go/src/github.com/DataDog/gohai/cpu/cpu.go:12 +0x47
main.Collect(0x10d2b6c0, 0x0, 0x0)
	C:/workspace/go/src/github.com/DataDog/gohai/gohai.go:32 +0xc6
main.main()
	C:/workspace/go/src/github.com/DataDog/gohai/gohai.go:44 +0x24

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
	c:/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
	c:/go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
	c:/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
	c:/go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
	c:/go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
	c:/go/src/pkg/runtime/proc.c:1445
```

**Comment by remh** [comment] 2015-11-19 21:18
Cannot reproduce on 5.6.1 closing for now. Let's reopen if it happens again.

**Closed by remh** 2015-11-19 21:18 UTC
Labels: bugfix, core, windows
